packages:
  - nextjs
  - nextjs/cdk
  - solidjs
  - solidjs/cdk

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@12.10.1

  - '@next/bundle-analyzer@16.4.0'
  - '@next/env@16.4.0'
  - '@next/swc-darwin-arm64@16.4.0'
  - '@next/swc-darwin-x64@16.4.0'
  - '@next/swc-linux-arm64-gnu@16.4.0'
  - '@next/swc-linux-arm64-musl@16.4.0'
  - '@next/swc-linux-x64-gnu@16.4.0'
  - '@next/swc-linux-x64-musl@16.4.0'
  - '@next/swc-win32-arm64-msvc@16.4.0'
  - '@next/swc-win32-x64-msvc@16.4.0'
  - next@16.4.0

overrides:
  postcss-selector-parser@<7.1.6: ^7.1.6
  semver: '>=7'
  seroval@<=1.6.2: ^1.6.3

trustPolicy: no-downgrade
