packages:
  - ./nextjs
  - ./nextjs/cdk
  - ./solidjs
  - ./solidjs/cdk

onlyBuiltDependencies:
  - unrs-resolver

overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  diff@<8.0.3: '>=8.0.3'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
